language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
# PHP 5.6 is not yet released, allow failures
matrix:
  allow_failures:
    - php: "5.6"
notifications:
  irc:
    channels:
        - "chat.freenode.net#dokuwiki"
    on_success: change
    on_failure: change
script: cd _test && phpunit --verbose --stderr
